### PR TITLE
another cyclow implementation of interval demo (using Iterator)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by krawaller** [comment]
Graflow looks really cool. This - `Chain(Ticker(1500), Iterator(lyrics, {cyclic: true}))` - is neat! :)

**Comment by ghost** [comment]
Thank you again!

**Comment by krawaller** [comment]
So, here's a curveball question, @pmros: is there a way to implement the Simpleclicker demo in a similar manner, using graflow to represent the clicks as a stream?

**Comment by ghost** [comment]
Do you mean something like this http://www.webpackbin.com/VJp5DjZuM? No cyclow, just graflow. 
Another graflow/cyclow implementations are possible but (IMHO) they are longer or more complex.

**Comment by krawaller** [comment]
I was thinking if there was a function to create a stream from DOM events, much like `Ticker(1500)` and `Counter(3)` initiates streams. Something like `DOM.select('button').events('click')` in xstream. 

Couldn't fully wrap my brain around what the graflow `Component` method actually does. In your webpackbin, the last Component (that does the `text.innerHtml` update), does that automatically call `next()` because it doesn't ask for it in the passed-in function?

**Comment by ghost** [comment]
I could add a new component factory to graflow like this:
```js
  const DomEvent = (el, e) => Component((v, next) => el.addEventListener(e, next))
```
`Component` is a component factory that can take a function as parameter. This functions can have two arguments:
- `v`: The input value.
- `next`: A function to output a value. It's something like yield in generators. If you don't use `next` function, your component will have no output.
So `Component` can create components with (zero or) one input and (zero or) one output. For a more complex component, you have to pass a object to `Component`.

I hope hat I have answered your questions. I'll improve graflow and cyclow documentation.

Thank you for your interest in graflow.

**Pull request merged**
